[package]
name = "rustfft_py"
version = "0.1.0"
edition = "2024"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
# "abi3-py39" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.9
pyo3 = { version = "0.25.1", features = ["extension-module", "abi3-py39"] }
numpy = "^0.25.0"
num = "^0.4.3"
rustfft = "^6.4.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
overflow-checks = true

[profile.dev]
opt-level = 3
