[project]
name = "rustfft"
version = "0.1.0"
description = "Python bindings for RustFFT"
readme = "README.md"
authors = [
    { name = "James Logan", email = "jlogan03@gmail.com" }
]
requires-python = ">=3.9, <3.14"
dependencies = [
    "numpy>=2",
]

[project.optional-dependencies]
dev = [
    "pytest >= 8.0",
    "coverage >= 7.3.2",
    "ruff >= 0.4.10",
    "pyright == 1.1.403",
    "mktestdocs >= 0.2.1",
]

[tool.maturin]
module-name = "rustfft._core"
python-packages = ["rustfft"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.ruff]
target-version = "py39"
line-length = 110

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.coverage.report]
fail_under = 100